### ISSUE TITLE
Possibly missing projects:cnrm-viewer for cnrm-controller-manager-logging

### ISSUE THREAD

**Issue by loudej** [GoogleCloudPlatform/blueprints#44]
After deploying this package, embedded in landing-zone/logging/bigquery-export...

https://github.com/GoogleCloudPlatform/blueprints/blob/07c398d254970eb982361db78402b5d8259c878f/catalog/log-export/org/bigquery-export/Kptfile#L2-L6

One of the resources remained in an error state with this message:
```
[
  "logging",
  "bqlogexportdataset",
  "Update call failed: error fetching live state: error getting ID for resource: error getting value from reference: error resolving reference field: error getting referenced resource from API server: error getting referenced resource projects/logging-129082878300 with GroupVersionKind resourcemanager.cnrm.cloud.google.com/v1beta1, Kind=Project from API server: projects.resourcemanager.cnrm.cloud.google.com \"logging-129082878300\" is forbidden: User \"system:serviceaccount:cnrm-system:cnrm-controller-manager-logging\" cannot get resource \"projects\" in API group \"resourcemanager.cnrm.cloud.google.com\" in the namespace \"projects\""
]
```

I added this to `landing-zone/namespaces/logging.yaml` which seems to fix that
 
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: projects/allow-resource-reference-from-logging
  name: allow-resource-reference-from-logging
  namespace: projects
roleRef:
  name: cnrm-viewer
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: cnrm-controller-manager-logging
    namespace: cnrm-system
    kind: ServiceAccount
```

based on seeing the similar role binding being applied to the networking sa

https://github.com/GoogleCloudPlatform/blueprints/blob/07c398d254970eb982361db78402b5d8259c878f/catalog/landing-zone/namespaces/networking.yaml#L108-L120
